---
title: "Thesis Data"
author: "Kangxin Bao - kb2900"
date: "November 1, 2017"
output: html_document
---

## Data import and preparation

```{r}
library(foreign)
cfps2014 <- read.dta(file.choose())
vars <- c("pid","pid_s","fid14","urban14","cfps2014_age", "cfps_gender", "p_income",
          "qea0", "qea204", "qea205y", "qm801", "qm802", "qm803", "qm1101", "qm1102",
          "qm1103", "qm1104", "qn8012", "qm501", "code_a_c1", "code_a_c2", 
          "code_a_c3", "code_a_c4", "code_a_c5", "code_a_c6", "code_a_c7",
          "code_a_c8", "code_a_c9", "code_a_c10")
sub14 <- cfps2014[, vars]
sub14 <- na.omit(sub14)

sub14_m <- subset(sub14, cfps2014_age > 19 & cfps2014_age < 56 & 
                    qea0 == "Married (having a spouse)" & 
                    qea204 != "Not applicable" & qea204 != "Refuse" & 
                    qea204 != "Unknown" & qea205y > -1 & qm801 > -1 & 
                    qm802 > -1 & qm803 > -1 & qm1101 > -1 & qm1102 > -1 & 
                    qm1103 > -1 & qm1104 > -1 & qn8012 > -1)

# year of marriage
sub14_m$qea205y <- 2014 - sub14_m$qea205y

# score on attitudes
sub14_m$att_fmstatus <- sub14_m$qm1101 + sub14_m$qm1102 + sub14_m$qm1103 + (6-sub14_m$qm1104)

# rename the meeting form
sub14_m$qea204 <- as.character(sub14_m$qea204)
sub14_m$qea204[sub14_m$qea204 == "Knew each other at school by ourselves"] <- "Knew by selves"
sub14_m$qea204[sub14_m$qea204 == "Knew each other at workplace by ourselves"] <- "Knew by selves"
sub14_m$qea204[sub14_m$qea204 == "Knew each other at place of residence by ourselves"] <- "Knew by selves"
sub14_m$qea204[sub14_m$qea204 == "Met each other at other places by ourselves"] <- "Knew by selves"
sub14_m$qea204[sub14_m$qea204 == "Met each other at other places by ourselves"] <- "Knew by selves"
sub14_m$qea204[sub14_m$qea204 == "Through marriage agency"] <- "Other"
sub14_m$qea204[sub14_m$qea204 == "Through the Internet"] <- "Other"
sub14_m$qea204[sub14_m$qea204 == "Other "] <- "Other"

# calculate number of children
sub14_m$code_a_c1 = ifelse(sub14_m$code_a_c1 == -8, 0, 1)
sub14_m$code_a_c2 = ifelse(sub14_m$code_a_c2 == -8, 0, 1)
sub14_m$code_a_c3 = ifelse(sub14_m$code_a_c3 == -8, 0, 1)
sub14_m$code_a_c4 = ifelse(sub14_m$code_a_c4 == -8, 0, 1)
sub14_m$code_a_c5 = ifelse(sub14_m$code_a_c5 == -8, 0, 1)
sub14_m$code_a_c6 = ifelse(sub14_m$code_a_c6 == -8, 0, 1)
sub14_m$code_a_c7 = ifelse(sub14_m$code_a_c7 == -8, 0, 1)
sub14_m$code_a_c8 = ifelse(sub14_m$code_a_c8 == -8, 0, 1)
sub14_m$code_a_c9 = ifelse(sub14_m$code_a_c9 == -8, 0, 1)
sub14_m$code_a_c10 = ifelse(sub14_m$code_a_c10 == -8, 0, 1)
sub14_m$children <- sub14_m$code_a_c1 + sub14_m$code_a_c2 + sub14_m$code_a_c3 +
  sub14_m$code_a_c4 + sub14_m$code_a_c5 + sub14_m$code_a_c6 + sub14_m$code_a_c7 +
  sub14_m$code_a_c8 + sub14_m$code_a_c9 + sub14_m$code_a_c10 
table(sub14_m$children)

colnames(sub14_m) <- c("id","spouse_id","family_id","urban","age","gender","income",
                       "marital", "first_meet", "year_marriage", "marital_sat",
                       "eco_sat", "housework_sat", "qm1101", "qm1102", "qm1103",
                       "qm1104", "ses", "ideal_child", "code_a_c1", "code_a_c2",
                       "code_a_c3", "code_a_c4", "code_a_c5", "code_a_c6", 
                       "code_a_c7", "code_a_c8", "code_a_c9", "code_a_c10",
                       "att_fmstatus", "number_child")

sub14_m <- subset(sub14_m, urban == "Urban" | urban == "Rural")
sub14_m <- subset(sub14_m, gender == "Male" | gender == "Female")

sub14_m$income <- sub14_m$income/1000
sub14_m$urban <- sub14_m$urban == "Urban"
sub14_m$gender <- sub14_m$gender== "Male"
sub14_m <- subset(sub14_m, first_meet == "Knew by selves" | first_meet == "Arranged by parents" | 
                    first_meet == "Introduced by friends" | first_meet == "Introduced by relatives")

sub14_m$first_meet <- factor(sub14_m$first_meet, levels = c("Arranged by parents", "Introduced by relatives", "Introduced by friends", "Knew by selves"))
tbl <- table(sub14_m$marital_sat, sub14_m$first_meet)
tbl
prop.table(tbl, 2)
chisq.test(tbl)
```

## Preliminary Analysis

```{r}
summary(sub14_m[, c("marital_sat", "first_meet", "att_fmstatus", "urban", "age", "gender", "income", "ses", "year_marriage", "number_child", "eco_sat","housework_sat")])

sub14_m %>%
  summarise(min_marsat = min(marital_sat) , median_marsat = median(marital_sat), mean_marsat = mean(marital_sat), 
            max_marsat = max(marital_sat), sd_marsat = sd(marital_sat),
            min_fmstatus = min(att_fmstatus) , median_fmstatus = median(att_fmstatus), mean_fmstatus = mean(att_fmstatus), 
            max_fmstatus = max(att_fmstatus), sd_fmstatus = sd(att_fmstatus),
            min_age = min(age) , median_age = median(age), mean_age = mean(age), 
            max_age = max(age), sd_age = sd(age),
            min_income = min(income) , median_income = median(income), mean_income = mean(income), 
            max_income = max(income), sd_income = sd(income),
            min_ses = min(ses) , median_ses = median(ses), mean_ses = mean(ses), 
            max_ses = max(ses), sd_ses = sd(ses),
            min_yearmar = min(year_marriage) , median_yearmar = median(year_marriage), mean_yearmar = mean(year_marriage), 
            max_yearmar = max(year_marriage), sd_yearmar = sd(year_marriage),
            min_nchild = min(number_child) , median_nchild = median(number_child), mean_nchild = mean(number_child), 
            max_nchild = max(number_child), sd_nchild = sd(number_child),
            min_eco_sat = min(eco_sat) , median_eco_sat = median(eco_sat), mean_eco_sat = mean(eco_sat), 
            max_eco_sat = max(eco_sat), sd_eco_sat = sd(eco_sat),
            min_hw_sat = min(housework_sat) , median_hw_sat = median(housework_sat), mean_hw_sat = mean(housework_sat), 
            max_hw_sat = max(housework_sat), sd_hw_sat = sd(housework_sat))

write.table(sum_var, file = "summary2.csv", sep = ",", col.names = NA, qmethod = "double")
```

```{r}
plot <- sub14_m[, c("first_meet", "marital_sat")]
library(ggplot2)
ggplot(plot, aes(x = marital_sat,  group = first_meet)) + 
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
  geom_text(size = 3, aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = -.5) +
  labs(x = "Marital satisfaction", y = "Percent", fill = "Satisfaction\nLevel") +
  facet_grid(~first_meet) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_hue(c=45, l=80) +
  theme(strip.background = element_rect(fill="#FFFFFF")) + 
  theme_bw()

```

## Linear Regression
```{r}
library(dplyr)
library(usdm)
library(car)
# variance check
X <- sub14_m[, c("first_meet", "att_fmstatus", "urban", "age", "income", "ses", 
                 "year_marriage", "number_child", "eco_sat","housework_sat")]
lm1 <- lm(marital_sat ~ first_meet, data=sub14_m)
lm2 <- lm(marital_sat ~ first_meet + att_fmstatus, data=sub14_m)
lm3 <- lm(marital_sat ~ first_meet + att_fmstatus + urban + age + gender + 
            income + ses + year_marriage + number_child + eco_sat + housework_sat,
         data=sub14_m)

summary(lm1)
summary(lm2)
summary(lm3)
vif(X)
vif(lm3)

```

## Ordinal Logistic Regression

```{r}
library(ordinal)
olog1 <- clm(as.factor(marital_sat) ~ first_meet, data=sub14_m)
summary(olog1)
exp(coef(olog1))

olog2 <- clm(as.factor(marital_sat) ~ first_meet + att_fmstatus, data=sub14_m)
summary(olog2)
exp(coef(olog2))

olog3 <- clm(as.factor(marital_sat) ~ first_meet + att_fmstatus + urban + age + gender +
               income + ses + year_marriage + number_child + eco_sat + housework_sat,
             data=sub14_m)
summary(olog3)
exp(coef(olog3))
```

## Test for collinearity

```{r}
library(dplyr)
library(usdm)
library(car)
# variance check
X <- sub14_m[, c("first_meet", "att_fmstatus", "urban", "age", "income", "ses", 
                 "year_marriage", "number_child", "eco_sat","housework_sat")]
lm <- lm(marital_sat ~ first_meet + att_fmstatus + urban + age + gender +
           income + ses + year_marriage + number_child + eco_sat + housework_sat,
         data=sub14_m)
summary(lm)
vif(X)
vif(lm(marital_sat ~ first_meet + att_fmstatus + urban + age + gender +
           income + ses + year_marriage + number_child + eco_sat + housework_sat,
         data=sub14_m))

lm2 <- lm(marital_sat ~ first_meet + att_fmstatus + urban + gender +
           income + ses + number_child + eco_sat + housework_sat,
         data=sub14_m)
summary(lm2)

anova(lm, lm2)

```

## Model Selection

```{r}
olog4 <- clm(as.factor(marital_sat) ~ first_meet + att_fmstatus + urban + gender +
               income + ses + number_child + eco_sat + housework_sat,
             data=sub14_m)
summary(olog4)
anova(olog3, olog4)
drop1(olog3, test="Chisq")

```

## Male and Female Separately

```{r}
library(ordinal)
sub14_male <- subset(sub14_m, sub14_m$gender == "Male")
sub14_female <- subset(sub14_m, sub14_m$gender == "Female")
olog_male <- clm(as.factor(marital_sat) ~ first_meet + att_fmstatus + age +
                   income + ses + year_marriage + number_child + eco_sat + housework_sat,
                 data=sub14_male)
summary(olog_male)

olog_female <- clm(as.factor(marital_sat) ~ first_meet + att_fmstatus + age + 
                     income + ses + year_marriage + number_child + eco_sat + housework_sat,
                   data=sub14_female)
summary(olog_female)

library("survival")
sub14_m$msat_cat <- ifelse(sub14_m$marital_sat > 3, TRUE, FALSE)

sub_pair1 = sub14_m[FALSE,]
sub_pair2 = sub14_m[FALSE,]
for (i in 1:1059){
  id <- sub14_male[i,1]
  for (j in 1:1013){
    sid <- sub14_female[j,2]
    if (id == sid){
      sub_pair1[i,] <- sub14_male[i,]
      sub_pair2[i,] <- sub14_female[j,]
    }
  }
}
sub_pair1 <- na.omit(sub_pair1)
sub_pair2 <- na.omit(sub_pair2)

sub_pair1$pair_id <- rep(1:436,rep(1,436))
sub_pair2$pair_id <- rep(1:436,rep(1,436))

sub_pair <- rbind(sub_pair1, sub_pair2)
sub_pair <- sub_pair[order(sub_pair$pair_id),]
sub_pair$msat_cat <- ifelse(sub_pair$marital_sat > 3, TRUE, FALSE)

clog_pair <- clogit(msat_cat ~ first_meet + att_fmstatus + strata(pair_id),
                    data=sub_pair)

clog_pair <- clogit(msat_cat ~ first_meet + att_fmstatus + gender +
                     income + ses + number_child + 
                    eco_sat + housework_sat + strata(pair_id), data=sub_pair)
summary(clog_pair)

with(sub_pair, table(first_meet, age, gender))
```

## Try mixed effect model using multinom

```{r}
library(nnet)
sub_pair$marital_sat <- relevel(as.factor(sub_pair$marital_sat), ref = 1)
m <- multinom(marital_sat ~ first_meet + att_fmstatus + age + gender + income + ses + 
             year_marriage + number_child + eco_sat + housework_sat + (1 | pair_id), 
           data = sub_pair)

summary(m)
z <- summary(m)$coefficients/summary(m)$standard.errors
z
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
```

## Mixed effect model using mlogit

```{r}
sub_pair$gender <- as.character(sub_pair$gender)
sub_pair <- subset(sub_pair, gender == "Male" | gender == "Female")
sub_pair$urban <- as.character(sub_pair$urban)
sub_pair <- subset(sub_pair, urban == "Rural" | urban == "Urban")
library(mlogit)
sub_pair_mlogit = mlogit.data(sub_pair, varying=NULL, choice="marital_sat", shape="wide")
mlogit <- mlogit(marital_sat ~ (1 | pair_id) + first_meet + att_fmstatus + 
                   gender + income + ses + number_child + eco_sat + housework_sat, 
                 data = sub_pair_mlogit, reference_level = "1")
summary(mlogit)

```
